mlswg/mls-architecture

README.md
Previously they pointed to mlswg.github.io/... but that doesn't work now that we use it for an actual homepage
=> Fix broken links to point directly to Github

draft-ietf-mls-architecture.md
Removing 2119 "MUST" as agreed in Paris.  Note that this is the minimal change and in another PR I will suggest removing as many lower case instances of must, should, etc. as possible.
=> removing 2119 language

draft-ietf-mls-architecture.md
This takes the "de_2119" idea a little bit further by making the requirements less aspirational.  For example instead of saying "MLS should be able to does this cool thing.." we just say "MLS does this cool thing".  Obviously, we will need to ensure that the claims are in fact true before we go final.
Also, by getting rid of lower case should, must, etc. we will avoid the "did you mean to upper case that" kind of questions that are bound to come with requirements documents.
There are also some other editorial nits here.
=> requirements language shift

draft-ietf-mls-architecture.md
* Change reference to XMPP to the current RFC.
* Change heading of "Deniability" section, which also discusses non-repudiation, to "Non-Repudiation and Deniability".
I wondered if that latter section should note that a third-party (ie, non-Member) cannot identify a sender from a given encrypted message, but then I wondered if that was the case or not.
=> Review from Dave Cridland

draft-ietf-mls-architecture.md
- Remove "join an existing group" from architecture doc, based on UserAdd having been removed from the protocol doc.
- Remove statement that message delivery cannot be correlated between AS identities and DS delivery channels. This seems generally very difficult to achieve. It may be possible at times, but does not seem to be grounded in discussions that we have had at the working group meetings.
- Note that federation requires compatible wire encodings.
- Note that communication with the AS requires TLS or alternative authentication.
- Note that out-of-band channels may facilitate detection of misbehaviour. 
- Some grammar fixes.
=> Updates based on a review in advance of the November 2018 IETF meeting.

draft-ietf-mls-architecture.md
We need an IANA considerations section even if we make no requests of them.  It's just part of the process and the section can be removed during the final publication phase.
=> adding IANA considerations section

draft-ietf-mls-architecture.md
Mostly lowercase everything and fixes a few misuses of "member" that were to restrictive.
=> Align language and syntax with protocol document

draft-ietf-mls-architecture.md
In the section _3.1.7. Compatibility with future versions of MLS_, the word "messages" is duplicated.
=> Removed duplicate word "messages"

draft-ietf-mls-architecture.md
As the title says, this PR doesn't change any text, but simply moves the sections on 
- `Message Secrecy and Authentication`
- `Forward and Post-Compromise Security`
- `Non-Repudiation vs Deniability`
to the `Security and Privacy Considerations` section in preparation for further PRs., where we plan on going into more detail on each of these properties.
This PR is joint work with @br-hale and @cascremers.
=> Move definitions of security properties to security considerations section

draft-ietf-mls-architecture.md
Reorganization of Section 3 in preparation of expanding text later.
This PR reorders text for a more logical structure, but does not meaningfully change any text. 
- Provide separate heading for assumptions.
- Client/endpoint compromise now precedes compromise of other nodes.
- Attacks outside of threat model moved to the end.
Joint work with @br-hale @kkohbrok .
=> Reorganize section 3

draft-ietf-mls-architecture.md
In the current definition, the AS is portrayed as a distinct service that could, for example run on a server separate from other MLS participants. However, in the MLS spec, it's more of an abstract layer that fulfills certain functionalities, some of which are likely to run on client devices. For example, an identity key that signs individual group-level signature keys could live in the secure element of a device. From the standpoint of the spec, that key would be part of the AS.
This PR changes the definition of the AS to reflect this, although there are of course multiple ways to tackle this.
The MLS spec is not explicit about the fact that it's the AS that's potentially responsible for message authentication, i.e. to bridge a potential gap between the key used to sign a message and the …
=> Rewrite AS definition to reflect its role in the Spec

draft-ietf-mls-architecture.md
Right now, the AS, DS, and "Functional Requirements" sections are subsections of the "General Setting" section.  As a result, "General Setting" and "Security and Privacy Considerations" were the only real top-level sections.  This PR pulls these subsections out to be top-level sections, which I think makes the table of contents more understandable.
Before:
```
```
After:
```
```
=> Make AS and DS top-level sections

draft-ietf-mls-architecture.md
Mainly focused on cleaning up grammar, but also fixing some things that have gone stale, like the idea that the MLS protocol is "abstract".
=> Edit pass on Abstract, Introduction, and General Setting

draft-ietf-mls-architecture.md
This edit got a little invasive, largely around the "ordering" requirements.  As was already pointed out the epoch numbering provides ordering to first order.  What is really needed is for the DS to select a single Commit per epoch.
=> Revise the DS section

draft-ietf-mls-architecture.md
This PR adds a short paragraph referencing the various academic works that has gone into MLS. 
The references to the various works still need to be cleaned up, which I will do once the list is complete. In particular, each reference needs to be checked for correctness (eprint version vs. publicized version) and then included as informal reference in the yaml header of the document.
=> Add references to academic work

draft-ietf-mls-architecture.md
I added a short section after `## Extensibility` discussing architectural issues for content framing and negotiation. It suggests [1] if the application doesn't have a more specific proposal.
[1] https://datatracker.ietf.org/doc/html/draft-mahy-mls-content-neg-00
=> Discuss content framing and negotiation

draft-ietf-mls-architecture.md
Reverts mlswg/mls-architecture#94
This has not been merged for a reason, namely I don’t want the dependency on an unpublished draft.
=> Revert "Discuss content framing and negotiation"

draft-ietf-mls-architecture.md
According to I-D Nits:
Checking nits according to https://www.ietf.org/id-info/checklist :
----------------------------------------------------------------------------
** The abstract seems to contain references ([I-D.ietf-mls-protocol]),
which it shouldn't.  Please replace those with straight textual mentions
of the documents in question.
** The document seems to lack a both a reference to RFC 2119 and the
recommended RFC 2119 boilerplate, even if it appears to use RFC 2119
keywords. 
RFC 2119 keyword, line 557: '...or forked group states MUST be deleted...'
=> Addressing I-D Nits

draft-ietf-mls-architecture.md
Made minor changes to the section of content and `application_data` framing.
Updated reference draft-mahy-mls-content-neg -> draft-mahy-mls-content-adv
The recommended mechanism is advertising content/media types, not a full negotiation mechanism.
=> Update: content negotiation -> content type advertisement

draft-ietf-mls-architecture.md
WGLC comments on Security Considerations Section
- Added discussion about significance of `basic` vs. `x509` credential types.
- Moved a paragraph about transport security in general into that section.
- Made text with list of metadata consistent with the metadata that is actually present in the protocol now.
- Moved Metadata Protection for Unencrypted Group Operations heading to just before the two paragraphs that actually discuss it.
- Added subsection "Integrity and Authentication of Custom Metadata" before the discussion about adding custom metadata to the AAD field.
- Noted that a websocket connection directly to the DS can be used instead of mobile host platform (ex: Apple, Google) native notifications in some environments.
- Fixed some typos.
=> WGLC changes in Privacy Considerations section.

draft-ietf-mls-architecture.md
The references at the end of the Security Considerations weren't in kramdown format. Fixed.
=> Fix security analysis references.

draft-ietf-mls-architecture.md
The Section `#### Authentication compromise: Ghost users and impersonations` has three recommendations, but the discussion rambles. The proposed text places topics related to each recommendation before that recommendation.
=> Reshuffle sentences in Ghost user discussion for better flow

draft-ietf-mls-architecture.md
There have been a lot of comments about the inclusion of WireGuard and Tor as potential secure transports, but I actually think it's confusing to cite IPsec as well for layering issues. We don't have a real praxis for using things that aren't application-layer style protocols for protecting this kind of traffic, so I don't think we should encourage these. I've trimmed it to just QUIC and TLS.
=> Remove cites to non-app layer secure transports.

draft-ietf-mls-architecture.md
Section 5 denotes the DS is responsible for providing the initial keying material: 
> As a directory service providing the initial keying material for clients to use. This allows a client to establish a shared key and send encrypted messages to other clients even if they're offline.
=> Retrieve initial keying material from DS, not AS

draft-ietf-mls-architecture.md
In Eric Vyncke's DISCUSS he correctly notes that LeafNode is used without being defined. I fixed that by just removing the term but more generally the problem is the use of "tree" without it being defined. Obviously the tree is an important concept but that's really a matter for mls-protocol not mls-architecture which is just concerned with group state as an abstract structure.
This change removes essentially all uses of the term tree except for:
- In the final security considerations section where I think it's OK in context.
- In this sentence
"A maximum number of steps that clients will move a secret tree ratchet forward in response to a single message before rejecting it."
I'm pretty sure that this can be reworded but I wasn't quite sure the best way.
=> Remove essentially all uses of "tree".

draft-ietf-mls-architecture.md
Change the definition of member to include only having been added to the group and not contributed to the group and explains what that might mean.
Note. this will need WG consensus to change.
=> Allow unconfirmed members. Fixes #205

draft-ietf-mls-architecture.md
This removes the text suggesting that the AS not generate keys. I agree that this is the best practice, but it's just such a standard practice that i think even mentioning the alternative creates confusion.
=> Remove recommendation not to have the AS generated keys

draft-ietf-mls-architecture.md
This is intended to tighten up the security considerations section a bit. It's mostly editorial but somewhat substantial changes.
=> Security considerations editorial

draft-ietf-mls-architecture.md
The sentence about homomorphic encryption introduced in PR #226 is speculative and not actionable.
=> Remove comment about homomorphic encryption

draft-ietf-mls-architecture.md
Incorporate a revised version of @rohan-wire's text from Issue #210. Instead of telling people they should use encrypted messages, instead explain the consequences of doing so or not.
=> Explain the impact of unencrypted operations. Fixes #210

draft-ietf-mls-architecture.md
=> Describe the risks of filtering at the DS

draft-ietf-mls-architecture.md
Hi,
I think there is a small mistake in [Figure 2](https://messaginglayersecurity.rocks/mls-architecture/draft-ietf-mls-architecture.html#figure-2), as it says in section [3.3](https://messaginglayersecurity.rocks/mls-architecture/draft-ietf-mls-architecture.html#section-3.3):
> When Alice wants to create a group including Bob, she first uses the DS to look up his initial keying material. 
The same is the case for section [3.4](https://messaginglayersecurity.rocks/mls-architecture/draft-ietf-mls-architecture.html#section-3.4)
=> fix figure 2

.github/workflows/ghpages.yml
The last two pull-requests failed because the version of `actions/upload-artifact` is too old (v2 instead of v4).
I have imported the new version of the action from [here](https://github.com/martinthomson/i-d-template/blob/main/template/.github/workflows/ghpages.yml) because the current `ghpages` workflow is adapted from [an old version (oct 2020) of it](https://github.com/martinthomson/i-d-template/blob/aa32825d42c99ef0eb7d40513379396f5af561ee/template/.github/workflows/ghpages.yml).
=> Update github action

draft-ietf-mls-architecture.md, rfc9750-draft.xml
I use the abbreviations for AS and DS most of the time after first use, with the major exception of heds and the like.
I also lower-cased Forward Secrecy and Post-Compromise Security
I haven't updated the XML yet, but if this looks good, I will harmonize after.
=> Use AS and DS most of the time. Fixes #279

draft-ietf-mls-architecture.md, rfc9750-draft.xml
@bifurcation PTAL. As before, I'll patch up the HTML once you approve the MD.
Here is my response to the RPC's comments:
> [rfced] Please let us know if any changes are needed for the
> following:
> 
> a) The following term was used inconsistently in this document.
> We chose to use the latter form. Please let us know any objections.
> 
> last resort (2 instances) / "last resort" (4 instances)
> (per Normative Reference RFC 9420)
This is fine.
> b) The following terms appear to be used inconsistently in this
> document. Please let us know which form is preferred.
> Would you like us to follow usage in Normative Reference RFC 9420
> ("The Messaging Layer Security (MLS) Protocol")?
> 
> Most of the terms listed below are also used in RFC 9420. We have
> marked them with asterisks ("*").
> …
=> Various minor consistency issues. Fixes #312
