mlswg/mls-architecture

- draft-ietf-mls-architecture.md
Text stolen from mls-protocol to let people know where to find the GH pages.
> Adding gh-info to Intro

- draft-ietf-mls-architecture.md
https://github.com/mlswg/mls-protocol/issues/96
> The DS ensures UIK identifier uniqueness

- draft-ietf-mls-architecture.md
There were some odd formulations in section 3.1.3.
I hope I addressed those issues without changing the intended meaning.
> Spelling fixes in the multi device section

- draft-ietf-mls-architecture.md
This PR aims to fix some odd formulations, whilst maintaining the intended meaning of the sentences.
> Spelling fixes in various sections.

- draft-ietf-mls-architecture.md
This PR addresses https://github.com/mlswg/mls-architecture/issues/62.
> Rename messaging service to service provider

- draft-ietf-mls-architecture.md
> Fix some grammar

- draft-ietf-mls-architecture.md
> Fixing outdated affiliation for contributor.

- draft-ietf-mls-architecture.md
Minor corrections throughout from joint edits by @kkohbrok, @br-hale, and @cascremers. 
Some description text added.
> Architecture Document Review 

- draft-ietf-mls-architecture.md
Fixes #91 
I have verified with all authors except for @tvdmerwe, whom I have pinged but not yet heard back from.  Hopefully the @mention here will get her attention :)
> Update author affiliations

- draft-ietf-mls-architecture.md
> Clarify that AS and DS can be realized in several ways

- draft-ietf-mls-architecture.md
Replaces #93 
Closes #92 
Not compact.
> Add a section on interoperability requirements.

- draft-ietf-mls-architecture.md
> Clarifications around PSKs and external operations

- draft-ietf-mls-architecture.md
This PR pulls in the CAP theorem-related discussion from https://github.com/mlswg/mls-protocol/pull/697 which is a more helpful way to frame DS design.
> Review sections 3-4.

- draft-ietf-mls-architecture.md
After exchanging some email with Albert while generating my Shepherd write-up, we agreed to move him to a contributor.
> Move Albert to Contributors

- draft-ietf-mls-architecture.md
> Review from OPSDIR.

- draft-ietf-mls-architecture.md
WGLC comments on Operation Requirements section.
- Added several overlooked requirements
> WGLC additions to Operational Requirements

- draft-ietf-mls-architecture.md
WGLC comments to Functional Requirements Section:
- Include text for case when external joins are authorized by members autonomously
- Fix formatting of one RECOMMENDATION section
- Reference the mls-federation document (informational)
> WGLC comments to Functional Requirements section

- draft-ietf-mls-architecture.md
> State admission control possibilities more accurately

- draft-ietf-mls-architecture.md
> Be more precise about loss and reordering

- draft-ietf-mls-architecture.md
Fixes #138 
Fixes #140 
Fixes #142 
Fixes #145 
Fixes #146 
Fixes #149 
Fixes #155 
Fixes #157
> Minor fixes for AD review, part 2

- draft-ietf-mls-architecture.md
This updates PR #163 from @bifurcation
> Add references for transport security protocols

- draft-ietf-mls-architecture.md
> Add a mention of IPsec as a secure channel

- draft-ietf-mls-architecture.md
> Address authentication failure cases

- draft-ietf-mls-architecture.md
> Discuss the privacy of a user's device set

- draft-ietf-mls-architecture.md
> Add missing newline before ## Endpoint Compromise

- draft-ietf-mls-architecture.md
Address IESG comments from Roman Danyliw and Yoav Nir (SEC)
Also address IESG telechat comments from Éric Vyncke (INT) because they overlap substantially
Partially addresses #178 (Roman Danyliw) - all DISCUSS issues except one already addressed in PR #180 (merged)
addresses some comments from #179 (Éric Vyncke) - DISCUSS issues both addressed 
Completely addresses #176 (Yoav Nir)
Addresses DISCUSS in #184 (Zaheduzzaman Sarker)
> Address comments and NITS from SEC and INT area

- draft-ietf-mls-architecture.md
This replaced PR #182 which has broken merge conflicts.
> Add new Terminology section

- draft-ietf-mls-architecture.md
I hope I got the citation format fine, and that the "é" won't be a problem.
I'm not sure about the integration in the "Cryptographic Analysis of the MLS Protocol" section, feel free to propose changes if you think of something better!
> Add new citation

- draft-ietf-mls-architecture.md
> Updating Srinivas Affiliation

- draft-ietf-mls-architecture.md
This is a pretty extensive rewrite of the General Setting section to provide a more comprehensive introduction (and a diagram) to how group formation works.
> Rewrite 'General Setting' section and example

- draft-ietf-mls-architecture.md
> Change rathr -> rather

- draft-ietf-mls-architecture.md
This covers the "Proposal" and "Commit" concerns in Eric Vyncke's discuss.
> Introduce the terms 'Proposal' and 'Commit'

- draft-ietf-mls-architecture.md
Reverts mlswg/mls-architecture#247. Merged by mistake, ongoing discussion.
> Revert "Make encrypted group operation recommendation conditional."

- draft-ietf-mls-architecture.md
- rfc9750-draft.xml
- Update MD to match accepted comments
- Revert rejected comments in XML
> Handle RPC copy edits

- draft-ietf-mls-architecture.md
- rfc9750-draft.xml
> Clarify text. Fixes #307

- draft-ietf-mls-architecture.md
- rfc9750-draft.xml
@bifurcation or @ekr please approve and merge if it isn't too late.
> Fix initial capitalization of push tokens
